name: flutter_base_project
description: "A skeleton project for flutter apps."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  dio: ^5.4.3+1
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  go_router: ^14.1.4
  shared_preferences: ^2.2.3
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
